### ISSUE TITLE
[BUG] Ace Pilot skins not showing properly

### ISSUE THREAD

**Issue by goatrb** [paradoxum-games/bugs#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Ace Pilot skin does not show the actual skin but only it's runway.

### Expected Behavior

The UI should show the Ace Pilot skin instead of the runway.

### Steps To Reproduce

1. Join the main lobby
2. Click on your inventory
3. On the towers section, click on Ace Pilot
4. Click on the Skins section
5. Click on an alternate skin for the tower

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://gyazo.com/cd30424de45d74c8d849477c7e56effa

**Comment by razuatix** [comment]
This issue will be resolved in the new shop / inventory update.
