### ISSUE TITLE
[BUG] Accelerator's Total Damage Counter Doesn't Update

### ISSUE THREAD

**Issue by watdahecc** [paradoxum-games/bugs#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Accelerator's total damage counter doesn't update despite it doing damage.

### Expected Behavior

Accelerator's total damage counter should update while doing damage.

### Steps To Reproduce

1. Place Accelerator
2. Wait for it to attack

### Platforms Affected

- [x] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

![Screenshot from 2022-03-12 16-23-04](https://user-images.githubusercontent.com/100169246/158035561-730b4673-73d0-4239-9ae5-bad746d8d0da.png)

**Comment by Awes-3** [comment]
resolved
