### ISSUE TITLE
[BUG] Level 3 Sniper does not have Lead Penetration

### ISSUE THREAD

**Issue by tomdaninja** [paradoxum-games/bugs#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sniper at Level 3 does not have Lead Penetration despite the upgrade description saying it does.

### Expected Behavior

Level 3 Sniper is supposed to damage Lead Enemies.

### Steps To Reproduce

1. Place Sniper in Hardcore Mode
2. Upgrade it to Level 3
3. Wait until Lead Enemies spawn and the Sniper attacks them.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

**Comment by Awes-3** [comment]
This has been fixed
