### ISSUE TITLE
[BUG] Military Base Not Giving Any Money From Hardcore Mode Kills/Damage

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever Military Base hits/kills an enemy in hardcore mode, the person with military base does not get any money.
Most likely a bug since military base used to give money upon damage.

### Expected Behavior

When enemy gets damaged by military base and then is later killed, it should give money to military base owner

### Steps To Reproduce

1. Join Hardcore match
2 Place Down military base in hardcore mode

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This is not an issue in other gamemodes, just hardcore.
![RobloxScreenShot20220312_225647971](https://user-images.githubusercontent.com/100378670/158036538-9f3db76d-f6b7-4e89-ad6a-70b505856e0d.png)
![RobloxScreenShot20220312_225651819](https://user-images.githubusercontent.com/100378670/158036540-ab50903c-4820-4988-a160-afbc0864ccf7.png)

**Comment by Awes-3** [comment]
resolved
