### ISSUE TITLE
[BUG] toxic gunner isn't slowing enemies down

### ISSUE THREAD

**Issue by AwesomeNess26108** [paradoxum-games/bugs#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toxic gunner shoots enemies, damages them, but their speed stays the same

### Expected Behavior

Enemies get slowed down by toxic gunner

### Steps To Reproduce

1. Join the main lobby
2. Equip toxic gunner
3. Join a game
4. Place toxic gunner
5. Wait for enemies to spawn
6. Toxic gunner does not effect their speed

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/N0KaN2R5PZQ video

**Comment by Awes-3** [comment]
not a bug: toxic gunner's slowdown has been nerfed heavily for now
