### ISSUE TITLE
[BUG] DJ Custom Music Button Missing / Not Appearing 

### ISSUE THREAD

**Issue by Peacefu1RB** [paradoxum-games/bugs#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The GUI for putting your custom music is missing, it should appear above the settings button in the bottom left corner

### Expected Behavior

It should appear above the settings button in-game

### Steps To Reproduce

1. Have the Custom DJ Music Gamepass
2. Join a match
3. Place DJ
4. Check bottom left corner above the settings button, there should be a Music icon, it is missing

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

![RobloxScreenShot20220312_172252685](https://user-images.githubusercontent.com/100227820/158037115-1131b978-7e44-486b-bc90-247496d034f3.png)
![RobloxScreenShot20220312_172249218](https://user-images.githubusercontent.com/100227820/158037117-4a17fee6-7d01-4ce1-a6b8-fe46a2ec4005.png)

**Comment by Awes-3** [comment]
This has been fixed

**Comment by PhoenixShay** [comment]
resolved
