### ISSUE TITLE
[BUG] Shared Cash Mechanic Working In Solo Mode 

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you are playing normal/molten/fallen/ gamemode in Solo, not only will you get money for dealing damage to the enemies but you will also get shared cash money that would only work in duo+. Because of this scout (and other towers that deal 1 damage) gives you 2 money per shot in Solo Mode.

### Expected Behavior

You should not be able to get shared cash while being in Solo Mode

### Steps To Reproduce

1 Join the game and choose any gamemode that isn't hardcore
2 Place down a tower (1 damage tower preferably)

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This works fine in hardcore mode
https://youtu.be/WQ67yOkpJ0w

**Comment by Awes-3** [comment]
This has been fixed
