### ISSUE TITLE
[BUG] Defense mechanic does not work at all

### ISSUE THREAD

**Issue by GreenReaper67** [paradoxum-games/bugs#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The defense mechanic on enemies will not work, the percentage on the enemies defense will not work and the base damage on the tower will be the same. 

### Expected Behavior

The defense mechanic should be able to reduce the income of damage, instead of it just not working, based on the equation of 

Original Damage ÷ (1 + Percentage Defense)

### Steps To Reproduce

1. Join a lobby
2. Join a game
3. Have a tower that does not have any special effects (ex. Militant, scout) and place it down
4. Check the damage on the tower
5. Check the defense percentage on an enemy
6. The enemy will not take reduced damage no matter the percentage, it will take the same damage as the base tower's damage.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Note: This was tested with one tower on one enemy on fallen mode, however, it should be able to take reduced damage regardless of the factors. In the video, the Militant should be able to do 3 damage to the boss, however, the boss was taking 4 damage per bullet, when doing the math, it should be able to do 3.

4 ÷ (1 + 30%) = 3.07692308

https://user-images.githubusercontent.com/100390961/158038578-999c9113-1a47-4f65-82d3-208a371e4ff6.mp4

**Comment by Awes-3** [comment]
not a bug: defense is rounded up no matter the value of the decimal
