### ISSUE TITLE
[BUG] Frost Blaster has no attack animation

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Frost blaster doesn't have any attack animation regardless of the level and enemy it shoots. It still damages the enemies even though it does not move.

### Expected Behavior

Frost blaster has an attack animation and aims at the enemies

### Steps To Reproduce

1. Join a map
2. Place down frost blaster
3. Let the frost blaster get in range of something
4. See the bug

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://user-images.githubusercontent.com/100169010/158039239-75290e95-b29c-4974-94dc-d675aa6db054.mp4

![image](https://user-images.githubusercontent.com/100169010/158039255-63b1ef9f-e580-4545-b4d5-3a4106c40c27.png)

**Comment by Awes-3** [comment]
resolved
