### ISSUE TITLE
[BUG] Lead Bosses Not "Speeding Up" When parts of their leads are taken off

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lead Bosses Are not speeding up when they get hit. After they get hit they stay at their same walking speed 

### Expected Behavior

Lead Bosses are supposed to "Speed up" when they get hit

### Steps To Reproduce

1. Join a Lobby
2. Go into a hardcore match
3. Make 1-2 Military Bases Hit a Lead

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/BqQ0GVaUFtY < Proof
Forgot To Do F9 for the console

**Comment by Awes-3** [comment]
resolved
