### ISSUE TITLE
[BUG] Enemies still spawn after you lose a game

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After you lose a game, enemies will continue to spawn if the current wave has not finished sending out the enemies only on that wave. The enemies that were present when you lost the game have disappeared, but not the ones that spawn after you die.

### Expected Behavior

Enemies don't continue to spawn after you lose a game

### Steps To Reproduce

1. Join a map
2. Die early on any round
3. Enemies will continue to spawn after dying

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/zukKwxjaLbw

**Comment by Awes-3** [comment]
resolved
