### ISSUE TITLE
[BUG] Defense Mechanic Affecting towers that only deal 2 damage per shot

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The damage done to enemies with defense seems not to work properly. For example ace pilot level 1 (does 2 damage per shot) now only deals 1 damage per shot to hefties with 25% defense.
I believe it's a bug since ace pilot level 1 always used to deal 2 damage to hefties.

### Expected Behavior

Towers that deal 1 or 2 damage shouldn't be affected by defense mechanic

### Steps To Reproduce

1. Join Hardcore game
2. Place Down Ace pilot level 1
3 Wait for "Hefty" enemy

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video of ace pilot dealing only 1 damage per shot to hefties.
https://youtu.be/aRJqwv1rk6I

Most likely caused by defense mechanic getting fixed and this instance getting ignored while the fix was being worked on
![hmm](https://user-images.githubusercontent.com/100378670/158057835-8b936b26-c021-40b8-92d5-090b461522e8.PNG)

**Comment by Eggrypted** [comment]
Made edits in the Issue so now it's more correct

**Comment by PhoenixShay** [comment]
no need to explicitly say that it's a bug in the title

**Comment by Awes-3** [comment]
resolved
