### ISSUE TITLE
[BUG] Golden Crook Boss's spawns (minions) overlapping

### ISSUE THREAD

**Issue by Sal7ss** [paradoxum-games/bugs#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Golden Crook Boss is eligible to spawn multiple entities (minions) at once, resulting in an overlap between the entities they spawn in.
A single GCB is able to spawn in multiple minions, while it originally spawned one at a time before this update.

### Expected Behavior

Golden Crook Boss should be spawning its entities after the existing one has been cleared out, instead of spawning multiple entities regardless. 

### Steps To Reproduce

1. Join the match.
2. Place down a Crook Boss.
3. Upgrade it to Lv.2
4. Repeat. 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [X] Phone

### Additional Information

![image](https://user-images.githubusercontent.com/100169455/158080068-af1e0bd7-832b-4593-ba9b-c13d960edbe3.png)

(Three minions have been spawned with two GCB placed down; Originally, it's supposed to spawn in two in total.)

**Comment by Awes-3** [comment]
resolved: crook boss has been given a limit of 3 simultaneous units spawned at a time per crook boss
