### ISSUE TITLE
Pyromancer burn damage is always 1 per tick and never increase in any level

### ISSUE THREAD

**Issue by PhotonRBLX** [paradoxum-games/bugs#14]
**Describe the bug**
Level 3 Pyromancer should have more burn damage per tick, but it doesn't get more burn damage per tick.

**To Reproduce**
1. Place level 3 Pyromancer, level 4 Pyromancer, and level 5 Pyromancer
2. Notice the burn damage per tick, it will always be 1 

**Expected behavior**
Level 3 Pyromancer should've done more burn damage per tick and not 1 per tick

**Screenshots**
https://www.youtube.com/watch?v=WIwiz5xp8Yc

**Comment by WikiaColors** [comment]
This was fixed I believe.
