### ISSUE TITLE
[BUG] Pyro's fire damage can't damage leads

### ISSUE THREAD

**Issue by AwesomeNess26108** [paradoxum-games/bugs#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pyro burns leads and the burn does no damage

### Expected Behavior

Leads can be damaged by fire, and pyro burns them

### Steps To Reproduce

1. Join the main lobby
2. Equip pyro
3. Join a hardcore match
4. Get a level 0 pyro on wave 14
5. Watch how it does no damage to the leads

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Pyro's non-burn damage (which it gains at level 2) CAN damage leads
https://youtu.be/yT4PhsAmJr8 pyro not burning leads
https://youtu.be/9xETUaTovIc damaging leads with non burn

**Comment by Awes-3** [comment]
resolved
