### ISSUE TITLE
[BUG] Enemy hp scaling is only visual

### ISSUE THREAD

**Issue by AwesomeNess26108** [paradoxum-games/bugs#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mysteries in hardcore appear to have 20 hp, but that is only visual and they actually have 10, as soon as they are damaged their actual hp will show.

### Expected Behavior

Mysteries should actually have 20 hp.

### Steps To Reproduce

1. Join the main lobby
2. Join a hardcore match
3. Get up to wave 17
4. Use a low damage tower (eg. scout) to shoot a couple of msteries
5. Watch their hp before and after they are damaged, notice how it goes from 20 to 9 when scout only does 1 damage, this is because it actually has 10 hp not the 20 it shows.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Not sure if this happens to other enemies that get scaled, such as mystery boss, and enemies in mega servers, so test that out too.
https://www.youtube.com/watch?v=aHhjASWAG5Q video (skip to 30 seconds)

**Comment by Awes-3** [comment]
resolved
