### ISSUE TITLE
[BUG] Fallen Titan Attack

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fallen Titan Stun seems to have AOE hitbox of his stun now instead the linear one which how it was before.
Fallen Titan also seems to freeze towers instead of doing usual stun (however this might be intentional)

### Expected Behavior

Fallen Titan stun shouldn't have AOE radius.  It also should stun normally instead of freezing towers.

### Steps To Reproduce

1 Join hardcore game
2 Get to wave 31+
3 Watch fallen titan's stun stun every tower around him

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video of the stun's hitbox:

https://youtu.be/_bTtUeBUHBw

**Comment by Awes-3** [comment]
resolved
