### ISSUE TITLE
[BUG] DPS and Firerate on high firerate towers fluctuate when spammed

### ISSUE THREAD

**Issue by tomdaninja** [paradoxum-games/bugs#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When high firerate towers such as Minigunner or Accelerator are spammed, their DPS fluctuates as they stop firing for a bit every second or so. This is not anything client-side such as lag or anything as I've talked with others and they have also seen this.

### Expected Behavior

The firerate should stay consistent.

### Steps To Reproduce

1. Join any map on any difficulty
2. Spam high firerate towers such as Minigunner or Accelerator (upgrade as far as possible to get highest firerate)
3. Place a Max Commander and use the COA Ability to achieve greatest and most visible effect
4. Pay attention to the Damage Counter on the towers or the HP of the enemies.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://user-images.githubusercontent.com/101480364/158273959-052bdff2-c2b7-4f61-b8f8-ee61fb84a0ac.mp4

If you pay attention to the Health Bar, you can see the damage being taken pause every now and then despite there only being one enemy.

**Comment by Awes-3** [comment]
Can you provide more information as to how many towers were spawned? I cannot reproduce this

**Comment by tomdaninja** [comment]
> Can you provide more information as to how many towers were spawned? I cannot reproduce this

I had somewhere from 28-30 Minigunners, 3-4 Commanders, and 1 DJ in my own testing.

**Comment by SneakyWolfy** [comment]
I wasn't able to reproduce this in the testing server, this may only happen in production. The above clip and all other instances were all from the live game.

**Comment by razuatix** [comment]
This has been escalated internally; we believe we've found the root cause of the issue. During the Entity System update, many components that utilized BaseValues now use Attributes. Attributes could be throttling on the server, so we'll try enemy health back to a BaseValue.

**Comment by razuatix** [comment]
Better demonstration of the issue: https://www.youtube.com/watch?v=JFHU5fxPj1w

**Comment by foxxerss** [comment]
I experienced this in the middle of a game when I wasn't spamming towers. I had 4 golden crook bosses, 1-2 of them were max, and I had 3 commanders and 1 dj, as well as my farms. I first noticed the towers were shooting slower around wave 23-24. I was going to finish the game and go to wave 40 with max accels and everything but they couldn't even kill the fallen guardians because of the dps drop.

**Comment by razuatix** [comment]
@Awes-3 has pushed a patch that has resolved this issue!

**Comment by tomdaninja** [comment]
I think the fix for this accidentally made the ROF bug worse in return.

Before the update, the ROF bug was about +0.03 on average. This is only a rough average but it was useful enough for calculating DPS.
After the Entity System Update, the ROF bug was about 0.008. This was far better but came at the cost of having the fluctuating DPS.
Now with the new fix i'm seeing that the ROF bug is back to 0.03
To demonstrate this here's a clip I just got. The Slow Boss with 1600 HP died in 33 seconds, which would mean that the Minigunner did about 48 DPS, which would mean that that the ROF addition here was about +0.033~

https://user-images.githubusercontent.com/101480364/160009198-227387e7-fc3b-49bf-98c1-1d2a8ec9eea9.mp4
