### ISSUE TITLE
[BUG] Soul Stealer Gets Permanently Stuck After Using Its Attack 

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Soul Stealers in Hardcore gamemode get perma stuck after taking a soul out of  a tower.

### Expected Behavior

Soul Stealers shouldn't get stuck after taking the soul out of a tower. 

### Steps To Reproduce

1 Join Hardcore Match
2 Reach Wave 45+
3 Watch Soul Stealer get stuck after using his soul steal attack. 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This issue doesn't happen when soul stealer tries to take the soul of a tower that doesn't have a soul (for example military base/turret.)

Video of them getting stuck:
https://youtu.be/oDMVU08FFAE

**Comment by Awes-3** [comment]
resolved
