### ISSUE TITLE
Placement Issues

### ISSUE THREAD

**Issue by angermode** [paradoxum-games/bugs#15]
Moon Base -- You cannot place any cliff towers on any cliff parts except the back.
Polluted Wasteland -- Unintentional Placement Spots
https://cdn.discordapp.com/attachments/588142500724867092/774794107411234858/Roblox_2020-11-07_19-31-35.mp4
https://cdn.discordapp.com/attachments/588142500724867092/774814996030029835/8ae226231e08d54075e4ad0c51160deb.png

Military base owned by 'BelowNatural', Named as 'minigunner' -- Failure to update tower information.
https://cdn.discordapp.com/attachments/588142500724867092/775215706265616404/Screenshot_20201108-221954_Discord.jpg

DJ - Multiple DJ's cause issues regarding upgrades
Reproduction: 
-you place 1 DJ with a tower nearby, giving the tower its buff
-you place another DJ near that tower, then upgrade it.
-remove the first DJ
---> the tower that was buffed by the first DJ receives no buffs.
https://cdn.discordapp.com/attachments/588142500724867092/774562219203624960/RobloxScreenShot20201107_160031181.png

Note: You cannot place under a tower under a player.

**Comment by KnownSH** [comment]
Thought I would add on to this post.

On the moon base map the cliffs you cant place cliff towers on you can place normal towers on.
[As seen here](https://cdn.discordapp.com/attachments/587355301674614854/775138349849116683/unknown.png)
