### ISSUE TITLE
[BUG] Commander's passive range does not properly update when upgrading or selling DJ

### ISSUE THREAD

**Issue by SneakyWolfy** [paradoxum-games/bugs#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you upgrade DJ, the towers the would be in its range does not get boosted. 

If you sell dj, towers that now are out of commander's passive range are still being boosted.

### Expected Behavior

Commander should boost the new towers in its ability range when its range is affected.

### Steps To Reproduce

1. Place a commander
2. Place a tower just outside of its range
3. Place a dj and boost commander to encompass the target tower.
4. The tower will not be boosted

5. Upgrade commander, the tower will now be boosted
6. Sell dj, the tower will still be boosted even if it's no longer in commanders range

### Platforms Affected

- [x] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://user-images.githubusercontent.com/64506745/158911813-7afe1091-89f5-4714-9945-410292fef854.mp4
https://user-images.githubusercontent.com/64506745/158911855-588ce52f-72c4-4592-925b-4923cb1caa30.mp4

**Comment by Awes-3** [comment]
resolved
