### ISSUE TITLE
[BUG] Commander's passive range does not match it's ability range.

### ISSUE THREAD

**Issue by SneakyWolfy** [paradoxum-games/bugs#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Commander's passive range appears to be spherical and its ability range appears to be cylindrical. This causes commander to sometimes not reach towers placed on high cliffs that will get boosted by Call to Arms.  

### Expected Behavior

It's expected that both towers within it's ability range are also within it's passive range. 

As there's no spherical indication of commander's range, it would be expected that the passive range should be updated to follow the same equation of it's active range. 

### Steps To Reproduce

1. Place a level 2 commander next to a high cliff
2. Place a cliff tower just on the edge of commanders range
3. The tower does not get affected by commander's passive boost
4. When using commander's active ability, the cliff tower will receive only the active ability buff (30%) but not the passive ability buff

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://user-images.githubusercontent.com/64506745/158912536-1119a9c6-4d45-4155-b410-6e88f0d840c7.mp4

**Comment by Awes-3** [comment]
resolved
