### ISSUE TITLE
[BUG] Enemies With Death Animation In Hardcore Have a Delay in Giving Money

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever you kill an enemy in hardcore that has his own death animation, the game will only give you money after the enemy completely disappears from the map and not when you kill it.

### Expected Behavior

When you kill an enemy in hardcore it should give you money the moment you kill it.

### Steps To Reproduce

1 Join Hardcore Match
2 Reach Wave 31+
3 Kill a Fallen Titan (he has a death animation)
4 Watch your money increase only after he disappears 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

**Comment by Awes-3** [comment]
resolved
