### ISSUE TITLE
[BUG] Military Base units can attack while "destoyed"

### ISSUE THREAD

**Issue by 2801Colours** [paradoxum-games/bugs#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Military Base unit is destroyed (when it reaches 0 health) it can still attack enemies, so long it has ranged attacks, such as the Railgun Tank.

### Expected Behavior

When destroyed, units should not be able to attack enemies.

### Steps To Reproduce

1. Join a game.
2. Place down a Military Base Level 3+
3. Wait for the Military Base unit to be destroyed.
4. Observe that if there is an enemy alive in range that the unit will attack it.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

Proof: https://cdn.discordapp.com/attachments/448368306676563969/955923123113455616/2022-03-22_15-15-11.mp4

**Comment by Awes-3** [comment]
resolved
