### ISSUE TITLE
[BUG] Some more music that is currently missing

### ISSUE THREAD

**Issue by danielcg1217** [paradoxum-games/bugs#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In addition to the audios already mentioned, the following audios are also missing due to Roblox's recent update: Manrobics, Cat Dance, and Breakdown.

### Expected Behavior

Expected the following audios to break and some to still exist in the game.

### Steps To Reproduce

1. Join the main lobby.
2. Use the emotes inventory to see which ones were silent.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

I cannot determine which other dances from the meme dances pack were affected as I do not own the gamepass and finding someone who did own it was frustrating.

**Comment by PhoenixShay** [comment]
Duplicate / can be handled under one issue - #175
