### ISSUE TITLE
[BUG] Ace pilot performing worse

### ISSUE THREAD

**Issue by Elite63719** [paradoxum-games/bugs#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The ace pilot seems to be dealing less DPS as shown in the video below. While the ace 2 days back was able to easily handle wave 5 in hardcore, currently it struggles way more. I am certain it is not a fluke either as I haven't been able to defeat wave 5 entirely for the past 2 hours in comparison to 2 days back when every attempt was successful. The ace pilot on the left also made its first shot at the enemy before it was in its range and I'm not certain about the second one (if that info is important).

### Expected Behavior

Ace pilot would perform the same a few days apart. 

### Steps To Reproduce

1. Join a game
2. Place an ace pilot
3. Compare its performance to a few days back

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video https://cdn.discordapp.com/attachments/935663394978152508/956365482376724490/solohcattemptdday1.mp4

**Comment by Awes-3** [comment]
resolved
