### ISSUE TITLE
[BUG] Killing all mysteries on specific waves auto-skips the wave

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Killing all mystery enemies on waves 16, 17, and 18 on fallen and molten mode makes those waves auto-skip, and continues to the next wave even if all enemies from that wave were not killed such as bosses spawned by the mysteries. 
This also happens on wave 11 and 12 on normal mode.

### Expected Behavior

Killing all mystery enemies on those waves should not auto-skip those waves 

### Steps To Reproduce

1. Join a map
2. Pick any difficulty 
3. Kill all the mystery enemies on one of the said waves
4. See that the wave auto-skips and continues to the next one

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Wave 18 on fallen mode
https://youtu.be/_letZn9jK5c

Wave 16 on molten mode
https://user-images.githubusercontent.com/100169010/160188497-f43f1585-3308-44d1-a018-ea4ab7218b96.mp4

![image](https://user-images.githubusercontent.com/100169010/160188554-0cac4a29-6ea7-4e48-b24d-0a0e07c18222.png)

**Comment by Awes-3** [comment]
not a bug
