### ISSUE TITLE
[BUG] Fallen Heroes spawn out of Mystery Bosses on wave 38

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fallen Heroes begin to spawn out of Mystery Bosses on wave 38 before they are supposed to naturally spawn on wave 39.

### Expected Behavior

Killing Mystery Bosses should not spawn Fallen Heroes on wave 38. They should spawn from Mystery Bosses on wave 39 and onward.

### Steps To Reproduce

1. Join a map
2. Get to wave 38 on fallen mode
3. Kill some mystery bosses 
4. RNG chance of getting fallen heroes 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

![RobloxScreenShot20220326_162316851](https://user-images.githubusercontent.com/100169010/160259344-8192f488-a53b-4d32-9ae6-b678e6e5542c.png)

**Comment by 2801Colours** [comment]
As far as I'm aware, this is intended, not a bug, since typically "minion" enemies can be spawned before their debut wave.

Case in point, the Molten Titan can spawn from the Mystery Boss from Wave 38 on Molten Mode, despite debuting on Wave 39.

**Comment by Awes-3** [comment]
not a bug
