### ISSUE TITLE
My cyber maid poop tower will not work.

### ISSUE THREAD

**Issue by Razuatix** [paradoxum-games/bugs#2]
**Describe the bug**
I cannot apply the "Cyber Maid Poop" skin to the tower!

**To Reproduce**
1. Try to equip the skin.
2. It will not work.
3. It throws an error crashing my entire computer causing a complete and utter world destruction 

**Expected behavior**
It's supposed to apply the skin.

**Comment by Razuatix** [comment]
I'll begin looking into this issue!

**Comment by Razuatix** [comment]
This issue is fake.

**Comment by Razuatix** [comment]
Oh my god, it's a real issue! I didn't know this existed, how foolish of me!

**Comment by Razuatix** [comment]
test

**Comment by Razuatix** [comment]
[](@everyone)

**Comment by Razuatix** [comment]
@everyone

**Comment by TheLapizSandwich** [comment]
Damn daniel stealing kids with your white vans
