### ISSUE TITLE
[BUG] Commander dialogue misspelled on certain waves

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Commander dialogue seems to have misspells on some waves. For example:
Wave 1 Fallen/Hardcore:
"Enemies are **approacing**"
Wave 30 Fallen:
"Watch out for the boulders he throws, they **sutn**!

If anyone one has any more feel free to comment them

### Expected Behavior

Commander dialogue shouldn't have misspells.

### Steps To Reproduce

1 Join a Fallen game
2 Look at commander's dialogue 
3 Notice the misspell at wave 1 and wave 30.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

**This was an issue before april fools update. It started when hardcore update released**

**Comment by Awes-3** [comment]
resolved
