### ISSUE TITLE
[BUG] The fallen king will be immobilized if an archer is stunned by his sword during the second phase.

### ISSUE THREAD

**Issue by Springfn** [paradoxum-games/bugs#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a fallen king hits an archer who is closer to him, he will be froze permanently. There is also a bug with boomers that if they explode near archers, they will not go away and will wander immobilized.

also, archer is immune to stun.

### Expected Behavior

If fallen king hits an archer in the second phase, it should not be frozen.

when boomers die in close proximity to an archer, they should disappear. 

### Steps To Reproduce

1. Join main lobby
2. Enter a elevator
3. Play fallen mode
4. Reach wave 34-40 (place an archer near a boomer on wave 34. Keep in mind that after it dies, it will be walking around with no health.) 
5. When the fallen king is half-health, move one archer closer to him.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://user-images.githubusercontent.com/100106973/161888031-b900a94d-9d36-4ef8-8017-eeccd4b12ddc.mp4

![Screenshot_4](https://user-images.githubusercontent.com/100106973/161888100-3d81d135-cb42-4c65-ac5b-f670c2f32620.png)

**Comment by Awes-3** [comment]
resolved
