### ISSUE TITLE
Mega Servers Don't Have a Price Increase For Towers/Upgrades.

### ISSUE THREAD

**Issue by Rhyssako** [paradoxum-games/bugs#22]
**Describe the bug** — 
In the original TDS, mega servers have a 1.2% price increase for towers, and upgrades according to the wikia.
https://cdn.discordapp.com/attachments/774342143196004362/776498934645653524/Screenshot_2020-11-12_112923.png

**To Reproduce** — *steps to reproduce the behavior!*
1. Go join a mega server in the lobby.
2. Look at the prices for the towers/upgrades.

**Expected behavior** — 
Prices should have a 1.2% increase.

**Screenshots** — 
https://cdn.discordapp.com/attachments/774342143196004362/776494041314492436/Screenshot_2020-11-12_110339.png **Lobby**

https://cdn.discordapp.com/attachments/774342143196004362/776494042623246406/Screenshot_2020-11-12_110444.png
**Mega**

**Comment by Razuatix** [comment]
This issue has been closed, this feature was removed in the latest update.
