### ISSUE TITLE
[BUG] Game Crashes When Placing Down A Tower On Windows Store Version of Roblox

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playing TDS on windows 10 store's version of roblox is unplayable. Whenever  you place down a tower, game crashes

### Expected Behavior

Game shouldn't crash when placing down a tower 

### Steps To Reproduce

1 Join TDS on windows store version of roblox
2 Place down a tower
3 Game Crashes

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This Issue only happens on microsoft store version of the game

**Comment by Awes-3** [comment]
resolved
