### ISSUE TITLE
Void Reaver gets stuck underground on Wrecked Battlefield

### ISSUE THREAD

**Issue by Emzyfrenzy** [paradoxum-games/bugs#23]
**Describe the bug**
When you play on wrecked battlefield in hardcore mode, if you do not do 1.4m total damage to the 2 void reavers or kill them before they reach the end of the bridge, the enemy will get stuck under the ground. This can be fatal, patirculary if it has already entered the phase where it speeds up.

**To Reproduce**
1. Play the wrecked battlefield map on hardcore mode
2.Reach Wave 50
2. Either Do less than 1.4million total damage on the void reavers by the time it reaches the bridge or not kill the fist void reaver before it reaches the bridge.
3. The void reaver will get stuck under ground once it passes this point.

**Expected behavior**
The void reaver continues to walk on the top of the path as normal as opposed to underground

**Screenshots/Evidence** 
https://cdn.discordapp.com/attachments/776494264204263466/776494427740569610/image2.png
https://cdn.discordapp.com/attachments/776494264204263466/776494427291910214/image1.png
https://cdn.discordapp.com/attachments/776494264204263466/776494425949077504/video0.mp4

**Additional context** 
I have yet to see this issue occur on another map so it seems to be wrecked only.

**Comment by SneakyWolfy** [comment]
Worth Mentioning that this only happens occasionally suggesting that there could be a second element causing this bug.

[Snippet from a video where it goes over the bridge with no issue](https://pasteboard.co/JA4ENc7.png )
[Video Source](https://www.youtube.com/watch?v=7ev6wUr72rM&t=1s)

**Comment by Razuatix** [comment]
This issue concerns a yet-to-be investigated flaw w/ spawning. I don't know when this'll get fixed but we'll keep the issue open, sadly there's no way for testers / players to view logs & report any further information aside from the aforementioned material.

**Comment by Razuatix** [comment]
I have pinned this issue to keep track of it & will report back once we've solved it.

**Comment by Razuatix** [comment]
I would like to add that the "Effects" issue on the client does not affect the spawning; as that's done completely on the server. The pictures attached are displaying a separate error concerning the enemy animator itself, this'll require a new investigation to determine the issue & resolve it.

**Comment by Razuatix** [comment]
We will continue to investigate this in hopes of releasing a hot-fix in the next update.
