### ISSUE TITLE
[BUG] Event enemies are frozen at spawn

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On every round of the easter event, the enemies are visually stuck at spawn. The towers can still see them as if they weren't bugged, but I can't see them. The enemies randomly teleport to where they should be and fix themselves after 10 seconds and then the process repeats itself after a new wave starts. 

### Expected Behavior

Enemies should not be frozen at spawn and should be seen walking to the middle.

### Steps To Reproduce

(This only happened to me once so I have no idea what happened to cause it)
1. Join easter event
2. See enemies frozen at their spawn

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This was being spammed in dev console
![image](https://user-images.githubusercontent.com/100169010/164348414-0bd3ce8c-967f-4126-8a61-9b8752e3f106.png)

https://youtu.be/Rqu1OIvm_yk

https://youtu.be/IZv1svVYe0g

**Comment by Awes-3** [comment]
does this still occur?

**Comment by foxxerss** [comment]
It hasn't happened since this game

**Comment by Awes-3** [comment]
closing this issue as it hasn't occured again
