### ISSUE TITLE
[BUG] Engineer's sentries have hitboxes enabled

### ISSUE THREAD

**Issue by Elite63719** [paradoxum-games/bugs#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When walking over sentries (war machine sentries in particular), the sentries are able to interact with the player. I am not certain whether lower level sentries have this issue to, but I am certain that war machine sentries do.

### Expected Behavior

While walking over sentries placed by the engineer, they will not collide with the player.

### Steps To Reproduce

1. Join any map
2. Place a level 6 Engineer
3. Walk over the sentries that it spawns

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video: https://cdn.discordapp.com/attachments/954955745802207282/970442438156120084/2022-05-01_14-47-37_1.mp4

**Comment by Awes-3** [comment]
resolved in next release
