### ISSUE TITLE
[BUG] Engineer interacts with player when building sentries

### ISSUE THREAD

**Issue by Elite63719** [paradoxum-games/bugs#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the engineer's placement animation for a sentry plays, if a player is standing over the engineer, the engineer will push the player. 

### Expected Behavior

The engineer's placement animation for sentries will not interact with the player.

### Steps To Reproduce

1. Join any match
2. Place an engineer
3. Stand on top of the engineer as it builds a sentry

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video: https://cdn.discordapp.com/attachments/954955745802207282/970442436960739398/2022-05-01_14-47-37.mp4

**Comment by Awes-3** [comment]
resolved in next release
