### ISSUE TITLE
[BUG] The tower’s “Total Spent” ignores Hardcore’s price increase

### ISSUE THREAD

**Issue by IJNYamato12** [paradoxum-games/bugs#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When placing down a tower in hardcore mode, the total spent will display the amount spent as if it weren't influenced by the price increase.

### Expected Behavior

The total spent of the placed tower would acknowledge hardcore’s price increase and display the correct amount of money spent.

### Steps To Reproduce

1. Join the main game 2. Go into a game of hardcore 3. Place down or save for a tower.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [X] Phone

### Additional Information

![ED35D6E5-5214-4C3B-98F4-15FDCC8CE726](https://user-images.githubusercontent.com/99991907/166172380-226e2998-74ec-4027-b18c-f670c7bfc1e0.jpeg)

**Comment by Awes-3** [comment]
resolved in next release
