### ISSUE TITLE
[BUG] Shield HP Doesn't Take Away Base HP When Enemy Gets To The End

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the enemy that has a shield gets to the end it won't deal any shield HP it has left (balloon enemy will always deal the maximum of 15 hp despite it having 25 hp in total)

### Expected Behavior

Shield HP should damage the base as well

### Steps To Reproduce

1 Join Hardcore
2 Let Balloon zombie leak
3 Notice it does incorrect amounts of damage

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

video of the issue:
https://youtu.be/AtCAQToKl6o

**Comment by Awes-3** [comment]
resolved in next release
