### ISSUE TITLE
Swarmer, Crook Boss, DJ Booth Weird Stats Display

### ISSUE THREAD

**Issue by PhotonRBLX** [paradoxum-games/bugs#29]
**Describe the bug**
Swarmer in level 1 and level 4 doesn't display anything, it's just blank for some reason
Crook Boss in level 2 says that the damage will be increased from 3 -> 3
DJ Booth in level 4 says that the range will be increased from 18 -> 18

**To Reproduce**
1. Place Swarmer, Crook Boss, and DJ Booth
2. Check Swarmer  level 1 and level 4 Stats
3. Check Crook Boss level 2 Stats
4. Check DJ Booth level 4 Stats

**Expected behavior**
Should display the correct Information

Swarmer 
Level 1: 1 -> 0.75 Tick, 3 -> 4 Sting Time
Level 4: 1 -> 2 Bee Damage, 0.75 -> 0.5 Tick, 4 -> 6 Sting Times, +Beehive Grenade

Crook Boss
Level 2: 9 -> 11 Range, +Hidden Detection

DJ Booth
Level 4:  +25% Range Boost

**Screenshots**
Swarmer
![image](https://user-images.githubusercontent.com/74334831/99137568-4b7a0000-265e-11eb-8d45-38b071c8e082.png)
![image](https://user-images.githubusercontent.com/74334831/99137573-59c81c00-265e-11eb-8e99-008567cca257.png)

Crook Boss
![image](https://user-images.githubusercontent.com/74334831/99137579-69476500-265e-11eb-97ea-a520d39ef436.png)

DJ Booth
![image](https://user-images.githubusercontent.com/74334831/99137584-75cbbd80-265e-11eb-9a42-2cc64d2cac4d.png)

**Additional context**
Every tower doesn't tell you which level you will be getting Hidden Detection on.

**Comment by Razuatix** [comment]
Hello, thank you for reporting this – I've fixed the issue concerning the "Hidden" stat not functioning. I'll continue to look into your report to see if we're able to push any fixes for this upcoming patch.
