### ISSUE TITLE
[BUG] Audio sliders are non-functional in-game

### ISSUE THREAD

**Issue by Aidoomed** [paradoxum-games/bugs#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Audio sliders in the Settings menu do not work when in a match.

### Expected Behavior

Audio sliders should work according to their percentage shown on-screen.

### Steps To Reproduce

1. Join any match on any map.
2. Check the Settings menu.
3. Go to Sound, and slide the sliders.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://user-images.githubusercontent.com/100172187/167216995-19d278b6-98b2-40b9-ad56-45b415eb133d.mp4

**Comment by razuatix** [comment]
Thx 👍🏻
