### ISSUE TITLE
[BUG] Can't exit out of party while in matchmaking circle

### ISSUE THREAD

**Issue by foxxerss** [paradoxum-games/bugs#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When standing in the matchmaking circle while in a party, you can't exit out of the party menu and clicking on any of the side buttons like the shop, inventory, and rewards do not work. If you go out of the circle, everything will work like normal and you can exit out of the party menu.

### Expected Behavior

You should be able to exit the party menu in the matchmaking circle as well as open your inventory, the shop etc.

### Steps To Reproduce

1. Join the main lobby
2. Go into the matchmaking circle
3. Create a party
4. Attempt to close out of the party menu while standing in the circle/open shop or inventory
5. See that you can't close the party menu or open anything 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/7jwjpba8IvU

![image](https://user-images.githubusercontent.com/100169010/167229857-1da71cc5-9b78-469d-b9bf-e29608c0f5e4.png)

**Comment by razuatix** [comment]
Most likely won't fix this, sorry!
