### ISSUE TITLE
Slasher Knife Throw deals no damage.

### ISSUE THREAD

**Issue by PhotonRBLX** [paradoxum-games/bugs#3]
**Describe the bug**
At level 2, Slasher has a knife throw ability, but the knife throw deals absolutely no damage at all.

**To Reproduce**
1. Place down Slasher
2. Upgrade it to level 2+
3. Notice how the knife throw deal no damage.

**Expected behavior**
The knife throw should able to deal damage.

**Screenshots**
https://cdn.discordapp.com/attachments/749720765150003241/772471251264077841/rydzhXX_-_Imgur.mp4

**Comment by TheLapizSandwich** [comment]
This mans knife dull as fuck pls fix give him a knife sharpener

**Comment by PhotonRBLX** [comment]
stfu

**Comment by PhotonRBLX** [comment]
> This mans knife dull as fuck pls fix give him a knife sharpener

stfu

**Comment by Razuatix** [comment]
stop posting useless shit
