### ISSUE TITLE
Issue w/ my "Medic" troop not upgrading.

### ISSUE THREAD

**Issue by Razuatix** [paradoxum-games/bugs#30]
**Describe the bug** — *a clear and concise description of what the bug is!*
I'm unable to upgrade my "Medic" troop past level 3

**To Reproduce** — *steps to reproduce the behavior!*
1. Place down the "Medic" troop.
2. Upgrade the "Medic" troop.
3. Medic will not upgrade.

**Expected behavior** — *a clear and concise description of what you expected to happen!*
It's supposed to upgrade to level 3!

**Comment by Razuatix** [comment]
I'll be looking into this issue soon!

**Comment by Razuatix** [comment]
This is a invalid issue; I will be closing this.

**Comment by theLMGN** [comment]
I'm also having this issue!
