### ISSUE TITLE
[BUG] Matchmaking queue has inaccurate amount of players queued

### ISSUE THREAD

**Issue by Rotteny420** [paradoxum-games/bugs#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The amount of players queued displays 0/4 when you queue up for a game of ducky hunt

### Expected Behavior

The amount of players should display 1/4 at least when you queue up for a game of ducky hunt

### Steps To Reproduce

1, Join the main lobby
2. Queue for Ducky Hunt with 4 people or by yourself
3. Observe the amount of players queued displayed

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://www.youtube.com/watch?v=4f4Lvs55YEI
This bug applies to both party mode and a solo queue

**Comment by Rotteny420** [comment]
![image](https://user-images.githubusercontent.com/98789244/167507822-3396f445-a920-497e-b4a3-3183470fabd3.png)
referring to this btw

**Comment by razuatix** [comment]
Most likely won't fix as in future versions of matchmaking we will no longer be using this same UI.
