### ISSUE TITLE
Crates Not Showing Skin

### ISSUE THREAD

**Issue by Rhyssako** [paradoxum-games/bugs#34]
**Describe the bug** — When you open a crate, it doesn't show the skin, so you have to click through every tower to find the new skin.

**To Reproduce** — 
1. Go to the crate tab.
2. Open a crate.

**Expected behavior** — *
When you open a crate, it's suppose to show the skin you received. 

**Screenshots** — *
https://cdn.discordapp.com/attachments/778798321317445652/778799518887706685/Roblox_2020-11-16_17-02-42.mp4
**(DEV CONSOLE AT END OF VIDEO)**

**Comment by Razuatix** [comment]
Thanks for reporting this, it appears this concerns an issue w/ the animation not properly loading, we'll work on adding precautions to prevent this.
