### ISSUE TITLE
Daily rewards countdown bug

### ISSUE THREAD

**Issue by heysoder12** [paradoxum-games/bugs#35]
**Describe the bug** — The bug seems to happen when the user's daily login rewards tries to countdown to 0 while the user is in the lobby when it does so.

**To Reproduce** — *steps to reproduce the behavior!*
1. Go to the game lobby
2. Wait until the countdown reaches 1
3. See error

**Expected behavior** — The rewards countdown should hit 0 and give the rewards, but instead is stuck on 1

**Screenshots**
![20201119_180211](https://user-images.githubusercontent.com/74710207/99652204-8206af00-2a92-11eb-8ac4-23dd8771a4ab.jpg)

**Comment by Razuatix** [comment]
Thanks for reporting this, due to a majority of the latest revision being rushed, this was not *fully* implemented. 

We'll be fixing it in the next patch!
