### ISSUE TITLE
[BUG] Fireworks emote gamepass is still on sale after 7/6

### ISSUE THREAD

**Issue by watdahecc** [paradoxum-games/bugs#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Fireworks emote gamepass was supposed to go off-sale on 7/6. However, it is still able to be purchased.

### Expected Behavior

The Fireworks gamepass should no longer be available to be purchased.

### Steps To Reproduce

1. Open the shop
2. Click on the gamepass advertisement
3. Gamepass can still be purchased

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

![Screenshot from 2022-07-09 15-37-40](https://user-images.githubusercontent.com/100169246/178120314-a6643a70-8fac-4c67-928d-1baf9d2f2562.png)
![Screenshot from 2022-07-09 15-37-24](https://user-images.githubusercontent.com/100169246/178120315-0bad276a-becb-48bf-b124-2100087d1463.png)
![Screenshot from 2022-07-09 15-28-47](https://user-images.githubusercontent.com/100169246/178120316-46e9542e-a5b8-42af-96d3-2c85ea0e8565.png)

**Comment by razuatix** [comment]
Will be taken off-sale this Monday.
