### ISSUE TITLE
Ability cooldown not appearing.

### ISSUE THREAD

**Issue by ShinyGemm** [paradoxum-games/bugs#39]
**Describe the bug** — 
When using an ability, the cooldown timer will not show on it. 

**To Reproduce** — 
1. Place any tower with an ability.
2. Upgrade to when it has that ability.
3. Use ability.
4. See error.

**Expected behavior** — 
The countdown for the ability should appear, and countdown to 0 to show when the ability is ready to use again.

**Comment by Razuatix** [comment]
I'll be putting this issue on our ClickUp - it should be patched in the next update.
