### ISSUE TITLE
Level Tower Issue

### ISSUE THREAD

**Issue by angermode** [paradoxum-games/bugs#4]
**New players cannot claim level based towers.** 
This includes Pursuit, Crook boss, Turret, and Mortar

There are currently no steps in reproducing the bug. People who reach the given level requirement simply do not have the "claim reward" option available.
https://cdn.discordapp.com/attachments/772437365188591626/772438088802107402/unknown.png

**Comment by Razuatix** [comment]
This has been fixed and a patch will be launched soon - this is a notification for others - please do not report this issue.

**Comment by Razuatix** [comment]
This issue has been resolved.
