### ISSUE TITLE
Military base does not sell upon clicking the "Sell" button

### ISSUE THREAD

**Issue by Devb596** [paradoxum-games/bugs#5]
**Description**
The military base does not sell upon clicking the sell button. It stops spawning, but the physical unit itself does not sell and the user does not get the tower space back.

**Steps to reproduce**
1. Place the military base
2. Sell the military base
3. Would produce and error and fail to comply

**GIF + Dev Console**
https://gyazo.com/d56c52b2eca14a494a3f938f0fec9ad9

**Comment by Razuatix** [comment]
I am not actively investigating this issue.

**Comment by Razuatix** [comment]
Issue will be fixed - "Sell" caused a unknown exception while attempting to delete units. This also caused the glitch that would allow  hundreds of units to be spawned causing major server latency.

**Comment by Razuatix** [comment]
I am now creating a fix for this issue; it'll be fixed for the next update.

**Comment by Razuatix** [comment]
I pushed a fix on our main repository but I'm reverting it so that I can verify if this affects "Unit" towers.

**Comment by Razuatix** [comment]
I will be marking this issue as closed; I've resolved the issue. My prior message concerning the reopening should be disregarded — our patch will be pushed this weekend.
