### ISSUE TITLE
[BUG] a

### ISSUE THREAD

**Issue by razuatix** [paradoxum-games/bugs#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

a

### Expected Behavior

a

### Steps To Reproduce

a

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

a

**Comment by razuatix** [comment]
Shayne 32

**Comment by PhoenixShay** [comment]
garbage
