### ISSUE TITLE
[BUG] Spam Clicking On a Tower Icon to Unequip it Causes the Game To Lag Heavily 

### ISSUE THREAD

**Issue by Eggrypted** [paradoxum-games/bugs#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spam clicking on tower icons in order to unequip them causes the game to lag Heavily. However while testing this I also noticed slight lag spikes while unequipping/equipping towers normally and I don't believe it should happen.

### Expected Behavior

Game shouldn't lag while unequipping the towers this way since sometimes you wanna get rid of your entire loadout.

### Steps To Reproduce

1 Join the main lobby
2 Make sure you have 4 or 5 towers in your loadout
3 Spam click on the 1st tower slot
4 Game starts to heavily lag

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

This issue happens in a lesser degree while you equip/unequip towers in normal way which can be seen in the video.
However spam clicking the 1st tower icon causes heavy lag.
https://www.youtube.com/watch?v=26nbdLNNVzg

**Comment by PhoenixShay** [comment]
this isnt really a bug but a debounce should be added anyway

**Comment by razuatix** [comment]
tagged as urgent in order to give precedence. this occurs as a result of many events being fired concurrently (which change the viewport to the newly selected troop). we made a rookie error, i'll see if we can push a quick patch under a support branch. if not, we'll defer this till the new hotbar is complete 👍🏻

**Comment by razuatix** [comment]
This issue will no longer exist in the new shop / inventory.
