### ISSUE TITLE
[BUG] Axe Throw Emote Glitch

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you use Axe Throw emote to hit a certain spot that is outside of an elevator. You would teleport to the inside of that elevator.

### Expected Behavior

The Axe is supposed to go back to you

### Steps To Reproduce

1. Join a Lobby
2. Go to the outside of an elevator
3. Use the Axe Throw emote to hit the certain spot

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/Gi_O9HJfMnA < Proof
![Screenshot 2022-03-01 162750](https://user-images.githubusercontent.com/100242981/156253222-4ccfeed7-7a2b-4ff6-80c1-ceaf53833322.png) < This is the certain spot you need to hit Axe Throw at
![Screenshot 2022-03-01 162912](https://user-images.githubusercontent.com/100242981/156253231-d036aeaa-39b5-47eb-acdf-ced5bbcc795b.png)

**Comment by PhoenixShay** [comment]
not necessarily a bug as there's nothing broken but probably not intended behavior

**Comment by razuatix** [comment]
it looks cool

**Comment by razuatix** [comment]
we will not fix. because it look cool
