### ISSUE TITLE
[BUG] Able to buy the coin skin from shop reset multiple times

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go to the store shop and when you proceed to the skin section when you go purchase the coin skin from the shop reset you can buy it again

### Expected Behavior

You are not supposed to buy the coin skin again

### Steps To Reproduce

1. Join a Lobby
2. Go to Store
3. Go To Skins
4. Buy the coin skin from shop reset
5. Go to Home
6. Go Back to Skins

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/IxoUaAbQH7U < Proof
![Screenshot 2022-03-01 165341](https://user-images.githubusercontent.com/100242981/156257189-0018d5cc-33d8-4e90-a11d-2330f5c40c5b.png) < Proof you can buy it again
![Screenshot 2022-03-01 165322](https://user-images.githubusercontent.com/100242981/156257222-dbf2d338-99f0-478a-b263-b135795fb2c4.png)
![Screenshot 2022-03-01 165256](https://user-images.githubusercontent.com/100242981/156257234-eddc7878-ff68-4296-9c1a-8b6d30502a2c.png)

**Comment by PhoenixShay** [comment]
#77 is related

**Comment by Mariokoo** [comment]
> 

ok
