### ISSUE TITLE
[VISUAL] Showing The Robux Prices of Game passes you already owned

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go into Robux and you go into game passes, it shows the Robux prices of game passes even when you already own them

### Expected Behavior

Ir shouldn't show the Robux prices when you own them

### Steps To Reproduce

1. Join a Lobby
2. Go into Store
3. Go to Robux
4. Go to game passes
5. Click a game pass you already own 

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/NvSMypMmpAI < Proof
![Screenshot 2022-03-01 171411](https://user-images.githubusercontent.com/100242981/156258754-b6bcc0ba-cbf5-4686-8152-1b2017e7253a.png) < Proof when you already own them
![Screenshot 2022-03-01 171450](https://user-images.githubusercontent.com/100242981/156258787-30d581ea-38a9-4276-8e29-3633a3b441c8.png)
![Screenshot 2022-03-01 171511](https://user-images.githubusercontent.com/100242981/156258791-a794fbf3-8b7f-4161-b029-71efb6ab912a.png)
![Screenshot 2022-03-01 171535](https://user-images.githubusercontent.com/100242981/156258801-f17e6b20-2b94-44df-859f-31b6bbc3105a.png)

**Comment by PhoenixShay** [comment]
should be grey and maybe say purchased?

**Comment by razuatix** [comment]
will defer till the new shop is completed, expected to come out later **_this month!_**

**Comment by Mariokoo** [comment]
> should be grey and maybe say purchased?

yea

**Comment by razuatix** [comment]
thx for reporting; as stated above this will not be fixed as it'll be resolved by the end of the month.
