### ISSUE TITLE
[BUG] Able to buy skins boxes multiples times when you already own all of the skins

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go into skins shop and when you own every skin in each box, you are still able to buy the boxes

### Expected Behavior

Each box should say "you already know every skin in this box" before buying

### Steps To Reproduce

1. Join s Lobby
2. Go into shop
3. Go to Skins
4. Buy a toy shop skin multiple times

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/bydZAOWv7aY < Proof
![Screenshot 2022-03-01 172645](https://user-images.githubusercontent.com/100242981/156260269-dc35aea1-bb7c-42df-b3f2-f7d313ffd5bd.png)
![Screenshot 2022-03-01 173113](https://user-images.githubusercontent.com/100242981/156260282-8edd173f-a960-450b-ba1a-efec1087ca61.png)
![Screenshot 2022-03-01 173130](https://user-images.githubusercontent.com/100242981/156260289-ddefc297-4586-474b-94ec-f0e7d0247d5f.png)
![Screenshot 2022-03-01 173146](https://user-images.githubusercontent.com/100242981/156260300-cbfa7f85-258d-4db9-9105-7a30813e5361.png)
![Screenshot 2022-03-01 173202](https://user-images.githubusercontent.com/100242981/156260307-036dbb2e-6740-494b-8e64-5c78040af96d.png)
^ Proof i already had all skins
![Screenshot 2022-03-01 173542](https://user-images.githubusercontent.com/100242981/156260566-99d208c8-74b2-4c3b-a9ac-2b7401a4a362.png)
![Screenshot 2022-03-01 173626](https://user-images.githubusercontent.com/100242981/156260570-bdc41c67-881f-4f3d-9d9c-e4e0db8bdcf1.png)

**Comment by PhoenixShay** [comment]
This can be consolidated into #75
