### ISSUE TITLE
[BUG] "Purchased" Indicator only indicates owned items rather than purchased items

### ISSUE THREAD

**Issue by Aidoomed** [paradoxum-games/bugs#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Store, the Towers & Emotes sections' "Purchased" indicators both only replicate the amount of Towers and Emoted owned respectively rather than how many are actually purchasable. 

### Expected Behavior

The "Purchased" indicator should only gather information on to what has already been purchased rather than what is owned, and should not reach beyond their respective numerical limits.

### Steps To Reproduce

1. Join the core lobby.
2. View the shop.
3. Count and compare how many Towers & Emotes you currently own compared to the amount of Towers & Emotes you've actually purchased. For those with any event Towers or event Emotes, the inconsistencies should be present.

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

Video link (SHOWS IN ACTION): https://user-images.githubusercontent.com/100172187/156261725-0949df82-672a-495d-8a53-85745184a4c8.mp4
Developer Console:
![RobloxScreenShot20220301_173753097](https://user-images.githubusercontent.com/100172187/156261781-ee9535e6-130c-4d30-890f-7222e0aba23b.png)
On Mobile:
![Screenshot_20220301-175040](https://user-images.githubusercontent.com/100172187/156262318-dc867c84-0c20-4d56-a3d3-bb5f6d27a7c4.png)

**Comment by PhoenixShay** [comment]
Not too sure what I'm supposed to be looking at in the screenshot, I could be blind. Could you clarify please?

**Comment by Aidoomed** [comment]
> 

The screenshot only clarifies that the situation is prevalent on Mobile devices as well.

**Comment by PhoenixShay** [comment]
Sorry, didnt see the video. This is just poor choice of words for the UI, should say "owned" instead of "purchased"

**Comment by razuatix** [comment]
Issue will no longer persist in the new shop / inventory.
