### ISSUE TITLE
Blocking Invisible UI Frame

### ISSUE THREAD

**Issue by SneakyWolfy** [paradoxum-games/bugs#8]
**Description**
There is a small frame (that is completely transparent) that will prevent you from clicking, scrolling, or dragging your camera when your cursor is over it.

**To Reproduce** 
1. You must first join any match
2. Near the middle, your cursor will turn black indicating an invisible frame
3. Clicking when your cursor is black will prevent all interactions

**Expected behaviour** 
To be able to click in the middle region of your screen with out any interruption.

**Screenshots**
[Visual indicating where the UI](https://pasteboard.co/JzXnAGM.png)
[Black Cursor suggesting the cursor is hovering over a UI:](https://pasteboard.co/JzXp087.png)

**Comment by Razuatix** [comment]
I'll begin investigating this soon, it's probably just a frame that has the "Active" property enabled. It could be either the DJ Booth or Upgrade interface(s)

**Comment by SneakyWolfy** [comment]
The active frame is believed to be the name-tag of the narrator.
