### ISSUE TITLE
[VISUAL/BUG] Getting charged for level towers you already have

### ISSUE THREAD

**Issue by Mariokoo** [paradoxum-games/bugs#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go into towers in stores, even when you have every tower you still get changed the amount the towers costs like as a new player

### Expected Behavior

Make the towers say "already own" or something similar to that

### Steps To Reproduce

1, Join a Lobby
2. Go to store
3. Go to towers
4. click on one of the towers

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/y1sc5ux3E5c < proof
![Screenshot 2022-03-01 215650](https://user-images.githubusercontent.com/100242981/156286864-10c35284-3661-44ca-8f7c-49e459b551d3.png) 
^proof you get charged
![Screenshot 2022-03-01 215750](https://user-images.githubusercontent.com/100242981/156286890-49db1431-14b0-4114-87fe-fedcf3f9e5d0.png)

**Comment by razuatix** [comment]
This issue will be resolved in the new shop / inventory.
