### ISSUE TITLE
[BUG] Closest targetting setting doesn't work properly

### ISSUE THREAD

**Issue by Elite63719** [paradoxum-games/bugs#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting the targetting setting on a tower to "closest", it begins to fire at enemies unpredicrably within it's range, not attacking closest enemies constantly. This happened when different types of enemies were within a tower's range (a mix of mysteries and bosses for example). I have not tested if the same issue occurs with a crowd of enemies of the same type (like a lot of abnormal bosses).

### Expected Behavior

When setting the targetting setting on a tower to "closest", it will always attack the enemy nearest to it

### Steps To Reproduce

1. Place a tower near the track to easily identify which enemies are nearest to it.
2. Set the targetting on the tower to closest
3. The tower begins to fire unpredictably at enemies within its range (occasionally)

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

Video: https://cdn.discordapp.com/attachments/634591007408783372/948417764392058900/2022-03-01_19-09-50.mp4 (targetting is set to closest)

**Comment by razuatix** [comment]
resolved in the entity system update
