### ISSUE TITLE
[BUG] Selecting skins returns you to the top of the tower menu

### ISSUE THREAD

**Issue by AwesomeNess26108** [paradoxum-games/bugs#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you click on a tower that is closer to the bottom of the tower menu (a tower you have to scroll down to see), to equip a skin for it, after equipping a skin, when you return to the tower selection menu, it scrolls you up to the top of the menu instead of where you were scrolled up to previously. This can be annoying when selecting skins for lost of towers at once.

### Expected Behavior

The tower selection menu would be scrolled to the same point you were at before you hit the "skins" button

### Steps To Reproduce

1. Join the main lobby
2. Open the inventory
3. Go to the tower selection menu
4. Scroll down a bit
5. Hit the "skins" button to select a skin
6. Hit the "skins" button again to return to the tower menu
7. You will now be scrolled up to the top of the tower menu, not where you were before you equipped skins

### Platforms Affected

- [ ] Desktop
- [X] Tablet
- [ ] Phone

### Additional Information

https://youtu.be/emdSF0DuNaM video (just the inventory part, the other part is for a different bug report)

**Comment by PhoenixShay** [comment]
Not necessarily a bug but probably not intended behavior

**Comment by razuatix** [comment]
This is an intentional feature; however, it will no longer exist in the new shop / inventory.
