### ISSUE TITLE
Skin Crate/ Tower-Based Issues

### ISSUE THREAD

**Issue by angermode** [paradoxum-games/bugs#9]
Equipped skin for Soldier (Dough Boy) does not animate properly.
Equipped skin for Minigunner (Toy) does not animate properly. Also does not shoot nerf bullets.
https://cdn.discordapp.com/attachments/774700800207093790/774700894687723540/image0.png
Equipped skin for Mortar (Bunny) does not work properly.
Equipped skin for Freezer (Mint Choco) does not work properly.

--Unknown if this is a current issue; Players are reporting Militant skin cannot be obtained with the pumpkin crate as of 11/9

--Platinum Crook is still in the game and should be removed
[Not Important] War Machine is broken in-game

**Comment by not-ferrum** [comment]
For mint choco freezer it functions normally and slows enemies perfectly fine.
It doesn't have much of an animation, but I'm pretty sure that's intended
The issue mint choco has is that its sound is bugged, so it sounds like some minigun. Not much of a major issue, but it hurts my ears
