### ISSUE TITLE
[BUG] Clipping through the elevator using the Transcendence Emote

### ISSUE THREAD

**Issue by huy3404** [paradoxum-games/bugs#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can clip through an elevator using the Transcendence Emote with the "Man" avatar body parts from Roblox (it doesn't work if you have the normal rectangle R6 one), demonstrated in the video below. 

### Expected Behavior

You should not be able to enter elevators without activating the timer that will descend the elevator and send you to your game.

### Steps To Reproduce

1. Go to Roblox Avatar -> Recent -> Body Parts
2. Equip the "Man" body parts, including arms, torso, and legs.
3. Join the main lobby
4. Enable Shift Lock
5. Go to any elevator and stand as close as possible to the side of it
6. Use the emote "Transcendence"
7. Rotate your camera 180 degrees and turn on Shift Lock.
8. Press G to stop using the emote and your character is now in the elevator.

### Platforms Affected

- [X] Desktop
- [ ] Tablet
- [ ] Phone

### Additional Information

The only way to get out of the elevator after you clipped through it using this method is to enter the elevator manually from the inside and exit it by pressing the "X" button.
I uploaded the video on youtube because the .mp4 file is too big.
Youtube Video:
https://www.youtube.com/watch?v=5pa7b0Qe6AY&feature=youtu.be&ab_channel=HuyQuang
Console Log:
https://gyazo.com/37e7b79eaaf996d99c313fd38e42014b

**Comment by PhoenixShay** [comment]
the lobby map itself is currently out of scope of reports
